
services:
  crawler:
    container_name: crawler
    build:
      context: ${PROJECT_ROOT}/engine/crawler
      dockerfile: Dockerfile

    working_dir: /app
    
    volumes:
      - ${PROJECT_ROOT}/engine/data:/app/data

    restart: unless-stopped

    networks:
      - app_network

    cpus: 1.0
    mem_limit: 512m

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  indexer:
    container_name: indexer
    build:
      context: ${PROJECT_ROOT}/engine/indexer
      dockerfile: Dockerfile

    working_dir: /app

    volumes:
      - ${PROJECT_ROOT}/engine/data:/app/data

    restart: unless-stopped

    networks:
      - app_network

    cpus: 0.5
    mem_limit: 512m

  # searcher:
  #   container_name: searcher
  #   build:
  #     context: ${PROJECT_ROOT}/engine
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${SEARCH_PORT:-7777}:7777"

  #   working_dir: /app

  #   # run indexer manually or on schedule
  #   command: npm run searchDev

  #   volumes:
  #     - ./engine:/app
  #     - ./engine/data:/app/data

  #   networks:
  #     - app_network

  #   restart: unless-stopped