
services:

  portainer:
    profiles:
      - monitoring
      - all
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "${PORTTRAINER:-9101}:9101"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  node-exporter:
    profiles:
      - monitoring
      - all
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "${NODE_EXPORTER:-9100}:9100"
    networks:
      - app_network

  prometheus:
    profiles:
      - monitoring
      - all
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ${PROJECT_ROOT}/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=24h"
      - "--web.enable-lifecycle"
    networks:
      - app_network
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  grafana:
    profiles:
      - monitoring
      - all
    image: grafana/grafana:8.2.4
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.petterssonhome.se/
      - GF_SERVER_DOMAIN=grafana.petterssonhome.se

    networks:
      - app_network
    ports:
      - "${GRAFANA_PORT:-3000}:3000"