FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=build /app/dist ./dist

COPY settings.json ./settings/settings.json
COPY crawlerFilter.yaml ./settings/crawlerFilter.yaml

CMD ["node", "dist/index.js"]